# Copyright 2025 The Torch-Spyre Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Symbolic value-tensor batch dim: gather + scatter compilation tests.

Regression tests for the two gaps fixed in pass_utils.py:

  GAP 1 — GATHER: ``_IndirectIndexFinder.indirect_indexing`` called ``int(size)``
    on the value-tensor's row count.  When dim-0 is symbolic (``mark_dynamic``),
    that discards the ShapeEnv upper bound and hands work-division a heuristic
    integer, causing wrong span / unsplit-dim decisions.

    Fix: ``finite_upper_or_none(size_expr)`` reads ``mark_dynamic(max=N)`` first;
    falls back to ``concretize_expr`` only when no finite ShapeEnv bound exists.

  GAP 2 — SCATTER: ``indirect_store_sizes`` called ``concretize_expr`` on every
    element of ``layout.size``.  Same problem: the ShapeEnv upper bound is ignored.

    Fix: identical ``finite_upper_or_none`` / ``concretize_expr`` pattern for
    each dim that maps to a scatter-index symbol.

Each scenario:
  1. Allocates the value / destination tensor with ``tensor.to("spyre", max=N)``
     so the storage is pre-sized for the ceiling and the SpyreTensorLayout is
     pinned to that ceiling.
  2. Calls ``mark_dynamic(dim=0, min=..., max=N)`` so Dynamo traces with a
     symbolic ``s0`` instead of a concrete size.
  3. Compiles and runs the full capture path (``capture_op_specs`` / ``check``),
     verifying that:
       (a) the compilation reaches the op-spec stage without crashing,
       (b) the op spec carries the expected indirect-access encoding
           (``GATHER_OP_SPEC`` / ``SCATTER_OP_SPEC``),
       (c) the SDSC bundle's indirect-access fields are structurally valid.
  4. Runs end-to-end on the real backend (``run_e2e``) — the same ``xfail``
     convention used by all indirect-access tests.

Multicore variants are generated by ``register_multicore_variants`` (same as
``test_indirect_access_gather.py`` / ``test_indirect_access_scatter.py``) so
work-division with a symbolic value-tensor batch dim is verified at every
supported SENCORES value.
"""

import os
import sys

import torch

import torch_spyre  # noqa: F401

sys.path.insert(0, os.path.dirname(__file__))
from indirect_access_common import (  # noqa: E402
    GATHER_OP_SPEC,
    SCATTER_OP_SPEC,
    capture_op_specs,
    op_spec_has_indirect_input,
    op_spec_has_indirect_output,
    register_multicore_variants,
    run_e2e,
)

# ---------------------------------------------------------------------------
# Shared tensor-creation helpers
# ---------------------------------------------------------------------------

# Reservation ceiling: value / destination pool has at most POOL_MAX rows.
POOL_MAX = 128
# Minimum runtime row count (must be > 2 so PyTorch does not specialise it).
POOL_MIN = 4
# Column width: 64 fp16 = 1 hardware stick.  Matches the standard indirect
# access test shape (M=128, N=64) so the same work-division constraints apply.
COLS = 64
# Number of index entries (concrete, not symbolic — only the *value* tensor's
# batch dim is made symbolic in these tests).
IDX_COUNT = 3


def _make_gather_tensors():
    """Return (x_dev, idx_dev) for the gather scenario.

    x_dev  : [POOL_MAX, COLS] fp16 on Spyre, reserved at POOL_MAX, marked dynamic
              on dim 0 with range [POOL_MIN, POOL_MAX].
    idx_dev: [IDX_COUNT] int32 on Spyre, concrete shape (not symbolic).

    The value tensor is moved with ``tensor.to("spyre", max=POOL_MAX)`` so its
    SpyreTensorLayout is computed against the ceiling and never changes across
    in-place resizes within [POOL_MIN, POOL_MAX].
    """
    torch.manual_seed(7)
    x_cpu = torch.rand(POOL_MAX, COLS, dtype=torch.float16)
    x_dev = x_cpu.to("spyre", max=POOL_MAX)
    torch._dynamo.mark_dynamic(x_dev, 0, min=POOL_MIN, max=POOL_MAX)

    idx = torch.randint(0, POOL_MIN, (IDX_COUNT,), dtype=torch.int32).to("spyre")
    return x_dev, idx


def _make_scatter_tensors():
    """Return (dst_dev, src_dev, idx_dev) for the scatter scenario.

    dst_dev : [POOL_MAX, COLS] fp16 on Spyre, reserved at POOL_MAX, marked
               dynamic on dim 0 with range [POOL_MIN, POOL_MAX].
    src_dev : [IDX_COUNT, COLS] fp16 on Spyre, concrete shape.
    idx_dev : [IDX_COUNT] int32 on Spyre, concrete shape.

    Indices are unique (``torch.arange``) so the overwrite-scatter is
    collision-free.  The destination is zero-initialised; values written are
    checked in the e2e leg.
    """
    torch.manual_seed(11)
    dst_cpu = torch.zeros(POOL_MAX, COLS, dtype=torch.float16)
    dst_dev = dst_cpu.to("spyre", max=POOL_MAX)
    torch._dynamo.mark_dynamic(dst_dev, 0, min=POOL_MIN, max=POOL_MAX)

    src_dev = torch.rand(IDX_COUNT, COLS, dtype=torch.float16).to("spyre")
    idx_dev = torch.arange(IDX_COUNT, dtype=torch.int32).to("spyre")
    return dst_dev, src_dev, idx_dev


# ---------------------------------------------------------------------------
# Gather scenario mixin
# ---------------------------------------------------------------------------

class _GatherSymbolicBatchDimScenarios:
    """Gather scenarios with a symbolic value-tensor batch dimension.

    Plain mixin (no TestCase base) — concrete collectable classes are produced
    by ``register_multicore_variants`` at the bottom of this file.
    """

    # -- core scenario: index_select with symbolic value-tensor dim 0 ------

    def test_gather_symbolic_value_tensor_batch_dim_reaches_op_spec(self):
        """Compilation reaches the op-spec stage and produces a gather op spec.

        Before the fix, ``int(size)`` on a symbolic row count either raised
        TypeError or returned the ShapeEnv lower bound (2), making the compiler
        believe the value tensor has 2 rows.  Work-division then built a plan
        valid only for 2 rows.

        After the fix, ``finite_upper_or_none`` extracts POOL_MAX from ShapeEnv
        and the compiler builds a plan valid for the full [POOL_MIN, POOL_MAX]
        range.
        """
        x_dev, idx_dev = _make_gather_tensors()
        self.check(
            lambda x, i: x.index_select(0, i),
            x_dev,
            idx_dev,
            expect=GATHER_OP_SPEC,
        )

    def test_gather_symbolic_value_tensor_batch_dim_e2e(self):
        """End-to-end gather with a symbolic value-tensor batch dim.

        Uses the same xfail convention as all other e2e indirect-access tests:
        the capture-path stage (above) runs strictly; e2e xfails when the
        backend does not yet support the pattern, and passes once it does.
        """
        x_dev, idx_dev = _make_gather_tensors()
        run_e2e(
            self,
            lambda x, i: x.index_select(0, i),
            x_dev,
            idx_dev,
        )

    def test_gather_symbolic_value_tensor_batch_dim_op_spec_structure(self):
        """The produced gather op spec has IndirectAccess on the value-tensor input.

        Verifies that the symbolic row count did not confuse the indirect-access
        classification: the value tensor must be flagged as an indirect input,
        not silently dropped to a direct-access path.
        """
        x_dev, idx_dev = _make_gather_tensors()
        with capture_op_specs() as captured:
            torch.compile(lambda x, i: x.index_select(0, i))(x_dev, idx_dev)

        op_specs = self.assert_reaches_op_spec(captured)
        self.assertTrue(
            any(op_spec_has_indirect_input(s) for s in op_specs),
            "value-tensor input must carry IndirectAccess; "
            "symbolic batch dim may have caused it to be treated as a direct op",
        )
        self.assertFalse(
            any(op_spec_has_indirect_output(s) for s in op_specs),
            "gather must not mark any output as IndirectAccess",
        )

    def test_gather_symbolic_value_tensor_batch_dim_resize_redispatch(self):
        """Shrink the value tensor within the reservation and re-dispatch.

        Verifies that a single compiled artifact handles both the max shape and
        a smaller concrete shape without recompiling.  The storage address and
        SpyreTensorLayout stay identical after ``resize_``, so the recompile
        guard never fires.
        """
        x_dev, idx_dev = _make_gather_tensors()
        kernel = lambda x, i: x.index_select(0, i)  # noqa: E731

        with capture_op_specs() as captured:
            torch.compile(kernel)(x_dev, idx_dev)
        self.assertTrue(captured, "first dispatch must reach op-spec stage")

        # Shrink to min size and re-dispatch — must reuse the same plan.
        x_dev.resize_(POOL_MIN, COLS)
        with capture_op_specs() as captured2:
            torch.compile(kernel)(x_dev, idx_dev)
        self.assertTrue(captured2, "second dispatch (min shape) must reach op-spec stage")


# ---------------------------------------------------------------------------
# Scatter scenario mixin
# ---------------------------------------------------------------------------

class _ScatterSymbolicBatchDimScenarios:
    """Scatter scenarios with a symbolic destination-tensor batch dimension.

    Plain mixin — concrete collectable classes are produced by
    ``register_multicore_variants`` at the bottom of this file.
    """

    # -- core scenario: index_put with symbolic destination dim 0 ----------

    def test_scatter_symbolic_dest_tensor_batch_dim_reaches_op_spec(self):
        """Compilation reaches the op-spec stage and produces a scatter op spec.

        Before the fix, ``concretize_expr(layout.size[0])`` returned a heuristic
        (e.g. 2) when dim 0 was symbolic, making the compiler believe the
        destination has 2 rows.  After the fix, ``finite_upper_or_none`` extracts
        POOL_MAX and the plan covers the full [POOL_MIN, POOL_MAX] range.
        """
        dst_dev, src_dev, idx_dev = _make_scatter_tensors()
        self.check(
            lambda dst, src, idx: dst.index_put([idx], src, accumulate=False),
            dst_dev,
            src_dev,
            idx_dev,
            expect=SCATTER_OP_SPEC,
        )

    def test_scatter_symbolic_dest_tensor_batch_dim_e2e(self):
        """End-to-end scatter with a symbolic destination-tensor batch dim."""
        dst_dev, src_dev, idx_dev = _make_scatter_tensors()
        run_e2e(
            self,
            lambda dst, src, idx: dst.index_put([idx], src, accumulate=False),
            dst_dev,
            src_dev,
            idx_dev,
        )

    def test_scatter_symbolic_dest_tensor_batch_dim_op_spec_structure(self):
        """The produced scatter op spec has IndirectAccess on the output.

        The destination's row is chosen at runtime from the index tensor;
        the indirect-access encoding must mark the output (destination) as
        IndirectAccess, not the source rows.
        """
        dst_dev, src_dev, idx_dev = _make_scatter_tensors()
        with capture_op_specs() as captured:
            torch.compile(
                lambda dst, src, idx: dst.index_put([idx], src, accumulate=False)
            )(dst_dev, src_dev, idx_dev)

        op_specs = self.assert_reaches_op_spec(captured)
        self.assertTrue(
            any(op_spec_has_indirect_output(s) for s in op_specs),
            "destination output must carry IndirectAccess; "
            "symbolic batch dim may have caused it to be treated as a direct op",
        )

    def test_scatter_symbolic_dest_tensor_batch_dim_resize_redispatch(self):
        """Shrink the destination tensor within the reservation and re-dispatch.

        Symmetric to the gather resize test: the SpyreTensorLayout is pinned to
        POOL_MAX, so a resize_ to POOL_MIN leaves the layout guard unchanged.
        """
        dst_dev, src_dev, idx_dev = _make_scatter_tensors()
        kernel = lambda dst, src, idx: dst.index_put(  # noqa: E731
            [idx], src, accumulate=False
        )

        with capture_op_specs() as captured:
            torch.compile(kernel)(dst_dev, src_dev, idx_dev)
        self.assertTrue(captured, "first dispatch must reach op-spec stage")

        dst_dev.resize_(POOL_MIN, COLS)
        with capture_op_specs() as captured2:
            torch.compile(kernel)(dst_dev, src_dev, idx_dev)
        self.assertTrue(captured2, "second dispatch (min shape) must reach op-spec stage")


# ---------------------------------------------------------------------------
# Register multicore variants (one class per SENCORES value)
# ---------------------------------------------------------------------------
register_multicore_variants(
    _GatherSymbolicBatchDimScenarios,
    "TestGatherSymbolicValueTensorBatchDim",
    globals(),
)

register_multicore_variants(
    _ScatterSymbolicBatchDimScenarios,
    "TestScatterSymbolicValueTensorBatchDim",
    globals(),
)

if __name__ == "__main__":
    from torch._inductor.test_case import run_tests

    run_tests()
